### ISSUE TITLE
Deprecate this repository?

### ISSUE THREAD

**Issue by erming** [jsonresume/resumeToText#3]
This repository is old and seems to have no reason to exist anymore.
Should we delete it?

Here's a list of old repositories:
- [resumeToHTML](https://github.com/jsonresume/resumeToHTML)
- [resumeToPDF](https://github.com/jsonresume/resumeToPDF)
- [resumeToText](https://github.com/jsonresume/resumeToText)
- [resumeToMarkdown](https://github.com/jsonresume/resumeToMarkdown)
- [jsondocs](https://github.com/jsonresume/jsondocs)

**Comment by mnibecker** [comment]
@erming out of curiosity where does this functionality now exists? Wasn't immediately apparent browsing through jsonresume's other repos.
